# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'FF_BaseWKWebVIewController' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FF_BaseWKWebVIewController
  
  pod "Masonry"

  target 'FF_BaseWKWebVIewControllerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FF_BaseWKWebVIewControllerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
